name: Publish Python Package

on:
  push:
    branches:
      - main
    paths:
      - "pyproject.toml"

# Add this permissions block
permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/main') && contains(github.event.head_commit.message, 'release')
    steps:
      - uses: actions/checkout@v3

      - name: Get version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(grep -m 1 'version = ' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
